M48
; DRILL file {KiCad 8.0.2} date 2024-12-26T16:14:04-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-26T16:14:04-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X128.0Y-49.9
T2
X106.0Y-44.0
X106.0Y-66.0
X130.0Y-44.0
X130.0Y-66.0
M30
