M48
; DRILL file {KiCad 8.0.2} date 2024-12-26T16:34:47-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-26T16:34:47-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X125.6Y-86.0
X140.6Y-86.0
X166.4Y-50.0
T2
X108.0Y-48.0
X108.0Y-88.0
X186.0Y-48.0
X186.0Y-88.0
M30
